### ISSUE TITLE
AttributeError: 'pysam.libcbcf.VariantFile' object has no attribute 'contigs'

### ISSUE THREAD

**Issue by caspargross** [spiralgenetics/truvari#30]
I installed the latest version 1.3 into a separate venv with all requirements (pysam 0.15.2)

For all runs i get the following error message:
```
2019-09-30 18:38:40,241 [WARNING] Excluding 1 contigs present in comparison calls header but not base calls.
Traceback (most recent call last):
  File "/mnt/SRV018/projects/external/promethion/sv_comparison/venv/bin/truvari", line 1044, in <module>
    main(sys.argv[1:])
  File "/mnt/SRV018/projects/external/promethion/sv_comparison/venv/bin/truvari", line 725, in main
    regions = GenomeTree(vcf_base, vcf_comp, args.includebed)
  File "/mnt/SRV018/projects/external/promethion/sv_comparison/venv/bin/truvari", line 528, in __init__
    name = vcfA.contigs[contig].name
AttributeError: pysam.libcbcf.VariantFile object has no attribute contigs
```
For test purposes i used the GIAB [reference](ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/) set compared to itself. Other combinations of vcf files with and without reference produced the same error. 

`truvari -b ../../reference_genomes/HG002_SVs_Tier1_v0.6.vcf.gz -c ../../reference_genomes/HG002_SVs_Tier1_v0.6.vcf.gz -o truvari_test --pctsim=0 `

Do you have any idea what might cause this?

**Comment by caspargross** [comment]
Everything works fine with release v1.2

**Comment by ACEnglish** [comment]
Sorry about that. We had a minor oversight in the liftover from pyvcf to pysam. v1.3.1 should address this bug.
